WebsitePemilu/WebsitePemilu/urls.py
from django.contrib import admin
from django.urls import path
from Pemilu.views import *
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', dashboard, name= 'dashboard'),
    path('', redirect_to_login),
    path('login/', user_login, name='login_user'),
    path('logout/', user_logout, name='logout_user'),
    path('daftar-pemilih', daftar_pemilih, name='daftar_pemilih'),
    path('data-pemilih/', data_pemilih, name= 'data_pemilih'),
    path('data-koordinator/', data_koordinator, name= 'data_koordinator'),
    path('verifikasi-nik/', verifikasi_nik, name='verifikasi_nik'),
    path('edit-koordinator/<int:coordinator_id>/', edit_koordinator, name='edit_koordinator'),
    path('delete-koordinator/<int:coordinator_id>/', delete_koordinator, name='delete_koordinator'),
    path('tambah-koordinator/', tambah_koordinator, name='tambah_koordinator'),
    path('tambah-pemilih/', tambah_pemilih, name='tambah_pemilih'),
    path('delete-pemilih/<int:pemilih_id>/', delete_pemilih, name='delete_pemilih'),
    path('edit-pemilih/<int:pemilih_id>/', edit_pemilih, name='edit_pemilih'),
    path('filter-data-pemilih/', filter_data_pemilih, name='filter_data_pemilih'),
    path('filter-data-koordinator/', filter_data_koordinator, name='filter_data_koordinator'),
    path('unduh-data-pemilih/', unduh_data_pemilih, name='unduh_data_pemilih'),
    path('unduh-data-koordinator/', unduh_data_koordinator, name='unduh_data_koordinator'),
    path('data-wilayah/', data_wilayah_view, name='data_wilayah'),
    path('setting/', setting_page, name='setting_page'),
    path('analisa/', analisa, name='analisa'),
    path('list-wilayah/', list_wilayah, name='list_wilayah'),
    path('isi-hasil-pemilu/<str:kecamatan_name>/<str:kelurahan_name>/', isi_hasil_pemilu, name='isi_hasil_pemilu'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WebsitePemilu/Pemilu/models.py
from django.db import models
from django.core.exceptions import ValidationError
import os
from django.conf import settings


# Tabel sebagai baseline data warga
class DataWarga(models.Model):
    # Informasi wilayah
    kabupaten = models.CharField(max_length=255)
    kecamatan = models.CharField(max_length=255)
    kelurahan = models.CharField(max_length=255)

    # Detail warga
    nkk = models.BigIntegerField()
    nik = models.BigIntegerField()
    nama = models.CharField(max_length=255)
    tempat_lahir = models.CharField(max_length=255)
    tanggal_lahir = models.DateField()
    sts_kawin = models.CharField(max_length=20)
    kelamin = models.CharField(max_length=1)
    alamat = models.CharField(max_length=255)
    rt = models.IntegerField()
    rw = models.IntegerField()
    disabilitas = models.IntegerField()
    ektp = models.CharField(max_length=255)
    tps = models.IntegerField()

    def __str__(self):
        return self.nama

# Tabel Koordinator
class DataKoordinator(models.Model):
    # Informasi wilayah kerja koordinator
    kabupaten = models.CharField('Kabupaten',max_length=255)
    kecamatan = models.CharField('Kecamatan',max_length=255)
    kelurahan = models.CharField('Kelurahan',max_length=255)

    # Detail koordinator
    nkk = models.BigIntegerField('NKK')
    nik = models.BigIntegerField('NIK')
    nama = models.CharField('Nama',max_length=255)
    tempat_lahir = models.CharField('Tempat Lahir',max_length=255)
    tanggal_lahir = models.DateField('Tanggal Lahir')
    sts_kawin = models.CharField('Status Kawin',max_length=20)
    kelamin = models.CharField('Jenis Kelamin',max_length=1)
    alamat = models.CharField('Alamat',max_length=255)
    rt = models.IntegerField('RT')
    rw = models.IntegerField('RW')
    disabilitas = models.IntegerField('Disabilitas')
    ektp = models.CharField('EKTP',max_length=255)
    tps = models.IntegerField('TPS')
    
    # Informasi tambahan koordinator
    tingkat_kerja_choices = [
        ('kabupaten', 'Kabupaten'),
        ('kecamatan', 'Kecamatan'),
        ('kelurahan', 'Kelurahan'),
        ('tps', 'TPS'),
        ('belum_ditentukan', 'Belum Ditentukan'),
    ]
    tingkat_kerja = models.CharField('Tingkat Kerja', max_length=20, choices=tingkat_kerja_choices, default='belum_ditentukan')

    kabupaten_bertugas = models.CharField('Kabupaten Bertugas',max_length=255, blank=True, null=True)
    kecamatan_bertugas = models.CharField('Kecamatan Bertugas',max_length=255, blank=True, null=True)
    kelurahan_bertugas = models.CharField('Kelurahan Bertugas',max_length=255, blank=True, null=True)
    tps_bertugas = models.IntegerField('TPS Bertugas',blank=True, null=True)

    
    foto_ktp = models.ImageField('Foto KTP', upload_to='foto_ktp/')
    jumlah_rekrutan = models.IntegerField('Jumlah Rekrutan',default=0)
    no_hp = models.CharField('No HP',max_length=30)

    def clean(self):
        if self.tingkat_kerja == 'kabupaten':
            if self.kecamatan_bertugas or self.kelurahan_bertugas or self.tps_bertugas:
                raise ValidationError("Koordinator tingkat kabupaten hanya boleh memiliki kabupaten_bertugas yang diisi.")
        elif self.tingkat_kerja == 'kecamatan':
            if not self.kabupaten_bertugas or not self.kecamatan_bertugas:
                raise ValidationError("Koordinator tingkat kecamatan harus memiliki kabupaten_bertugas dan kecamatan_bertugas yang diisi.")
            if self.kelurahan_bertugas or self.tps_bertugas:
                raise ValidationError("Koordinator tingkat kecamatan tidak boleh memiliki kelurahan_bertugas atau tps_bertugas.")
        elif self.tingkat_kerja == 'kelurahan':
            if not all([self.kabupaten_bertugas, self.kecamatan_bertugas, self.kelurahan_bertugas]):
                raise ValidationError("Koordinator tingkat kelurahan harus memiliki semua field wilayah bertugas yang diisi.")
            if self.tps_bertugas:
                raise ValidationError("Koordinator tingkat kelurahan tidak boleh memiliki tps_bertugas.")
        elif self.tingkat_kerja == 'tps':
            if not all([self.kabupaten_bertugas, self.kecamatan_bertugas, self.kelurahan_bertugas, self.tps_bertugas]):
                raise ValidationError("Koordinator tingkat TPS harus memiliki semua field wilayah bertugas dan tps_bertugas yang diisi.")
    
    def save(self, *args, **kwargs):
        self.full_clean()
        
        nik = str(self.nik)
        self.foto_ktp.name = f'foto_ktp_{nik}.jpg'
        
        super().save(*args, **kwargs)
    
    def delete(self, *args, **kwargs):
        if self.foto_ktp:
            file_path = os.path.join(settings.MEDIA_ROOT, str(self.foto_ktp))
            if os.path.exists(file_path):
                os.remove(file_path)

        super().delete(*args, **kwargs)
    
    def __str__(self):
        return f"{self.nama} - ID: {self.id}"

# Tabel Daftar Pemilih
class DataPemilih(models.Model):
     # Informasi wilayah  pemilih
    kabupaten = models.CharField('Kabupaten',max_length=255, blank=True, null=True)
    kecamatan = models.CharField('Kecamatan',max_length=255, blank=True, null=True)
    kelurahan = models.CharField('Kelurahan',max_length=255, blank=True, null=True)

    # Detail pemilih
    nkk = models.BigIntegerField('NKK',blank=True, null=True)
    nik = models.BigIntegerField('NIK',blank=True, null=True)
    nama = models.CharField('Nama',max_length=255, blank=True, null=True)
    tempat_lahir = models.CharField('Tempat Lahir',max_length=255, blank=True, null=True)
    tanggal_lahir = models.DateField('Tanggal Lahir',blank=True, null=True)
    sts_kawin = models.CharField('Status Kawin',max_length=20, blank=True, null=True)
    kelamin = models.CharField('Jenis Kelamin',max_length=1, blank=True, null=True)
    alamat = models.CharField('Alamat',max_length=255, blank=True, null=True)
    rt = models.IntegerField('RT',blank=True, null=True)
    rw = models.IntegerField('RW', blank=True, null=True)
    disabilitas = models.IntegerField('Disabilitas',blank=True, null=True)
    ektp = models.CharField('EKTP',max_length=255, blank=True, null=True)
    tps = models.IntegerField('TPS',blank=True, null=True)

    # Informasi tambahan pemilih
    foto_ktp = models.ImageField('Foto Ktp',upload_to='foto_ktp/')
    koordinator = models.ForeignKey(DataKoordinator, on_delete=models.CASCADE)

    def __str__(self):
        return self.nama  # Atau gunakan informasi lain yang sesuai

from django.db import models

class PengaturanWilayah(models.Model):
    kabupaten_bangka = models.BooleanField('Kabupaten Bangka',default=False)
    kabupaten_bangka_selatan = models.BooleanField('Kabupaten Bangka Selatan',default=False)
    kabupaten_bangka_tengah = models.BooleanField('Kabupaten Bangka Tengah',default=False)
    kabupaten_bangka_barat = models.BooleanField('Kabupaten Bangka Barat',default=False)
    kota_pangkal_pinang = models.BooleanField('Kota Pangkal Pinang',default=False)
    kabupaten_belitung = models.BooleanField('Kabupaten Belitung',default=True)
    kabupaten_belitung_timur = models.BooleanField('Kabupaten Belitung Timur',default=True)
    

class DataPemilu(models.Model):
    kabupaten = models.CharField(max_length=255)
    kecamatan = models.CharField(max_length=255)
    kelurahan = models.CharField(max_length=255)
    tps = models.CharField(max_length=255)
    calon_1_2019 = models.IntegerField()
    calon_2_2019 = models.IntegerField()
    calon_3_2019 = models.IntegerField()
    suara_Partai_2019 = models.IntegerField()
    calon_1_2024 = models.IntegerField()
    total_suara_2024 = models.IntegerField()

    def __str__(self):
        return f"{self.kabupaten} - {self.kecamatan} - {self.kelurahan} - {self.tps}"

WebsitePemilu/Pemilu/forms.py
from django import forms

class PendaftaranPemilihForm(forms.Form):
    nik = forms.CharField(label='NIK')
    # Tambahkan field-form lainnya sesuai kebutuhan
    
class PendaftaranKoordinatorForm(forms.Form):
    nik = forms.CharField(label='NIK')
    # Tambahkan field-form lainnya sesuai kebutuhan
    
from django import forms
from .models import DataKoordinator
from .models import DataPemilih

# Data wilayah yang Anda sediakan sebelumnya
dataWilayah = {
    "Belitung": {
        "Membalong": ["Bantan", "Gunung Riting", "Kembiri", "Lassar", "Membalong", "Mentigi", "Padang Kandis", "Perpat", "Pulau Seliu", "Pulau Sumedang", "Simpang Rusa", "Tanjungrusa"],
        "Tanjung Pandan": ["Air Ketekok", "Air Pelempang Jaya", "Air Rayak", "Air Merbau", "Air Saga", "Buluh Tumbang", "Dukong", "Juru Seberang", "Perawas", "Kampong Damai", "Kota", "Lesung Batang", "Paal Satu", "Pangkallalang", "Parit", "Tanjungpendam"],
        "Badau": ["Air Batu Buding", "Badau", "Cerucuk", "Ibul", "Kacang Butor", "Pegantungan", "Sungai Samak"],
        "Sijuk": ["Air Selumar", "Air Seruk", "Batu Itam", "Keciput", "Pelepak Pute", "Sijuk", "Sungai Padang", "Tanjong Tinggi", "Tanjung Binga", "Terong"],
        "Selat Nasik": ["Petaling", "Pulau Gersik", "Selat Nasik", "Suak Gual"],
    },
    "Belitung Timur": {
        "Damar": ["Air Kelik", "Burong Mandi", "Mempaya", "Mengkubang", "Sukamandi"],
        "Dendang": ["Balok", "Dendang", "Jangkang", "Nyuruk"],
        "Gantung": ["Batu Penyu", "Gantung", "Jangkar Asam", "Lenggang", "Lilangan", "Limbongan", "Selingsing"],
        "Kelapa Kampit": ["Buding", "Cendil", "Mayang", "Mentawak", "Pembaharuan", "Senyubuk"],
        "Manggar": ["Baru", "Bentaian Jaya", "Buku Limau", "Kelubi", "Kurnia Jaya", "Lalang", "Lalang Jaya", "Mekar Jaya", "Padang"],
        "Simpang Pesak": ["Dukong", "Simpang Pesak", "Tanjung Batu Itam", "Tanjung Kelumpang"],
        "Simpang Renggiang": ["Aik Madu", "Lintang", "Renggiang", "Simpang Tiga"],
    },
}

from django import forms

from django import forms

class KoordinatorForm(forms.ModelForm):
    class Meta:
        model = DataKoordinator
        exclude = ['jumlah_rekrutan']
    
    def save(self, commit=True):
        instance = super().save(commit=False)
        nik = str(self.cleaned_data['nik'])
        instance.foto_ktp.name = f'foto_ktp_{nik}.jpg'

        if commit:
            instance.save()

        return instance

    def clean(self):
        cleaned_data = super().clean()
        kabupaten_bertugas = cleaned_data.get('kabupaten_bertugas')
        kecamatan_bertugas = cleaned_data.get('kecamatan_bertugas')
        kelurahan_bertugas = cleaned_data.get('kelurahan_bertugas')

        if not kabupaten_bertugas:
            # Set a default value for kecamatan and kelurahan if kabupaten is empty
            cleaned_data['kecamatan_bertugas'] = 'none'
            cleaned_data['kelurahan_bertugas'] = 'none'
        
        # Tambahkan validasi khusus jika diperlukan
        return cleaned_data



class PemilihForm(forms.ModelForm):
    class Meta:
        model = DataPemilih
        fields = '__all__' 

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['koordinator'].queryset = DataKoordinator.objects.all()
        self.fields['koordinator'].widget = forms.HiddenInput()
        #self.fields['koordinator'].widget = forms.Select(choices=[('', 'Koordinator')] + list(DataKoordinator.objects.values_list('id', 'nama')))
    
    def clean(self):
        cleaned_data = super().clean()
        # Tambahkan validasi khusus jika diperlukan
        return cleaned_data
    
from django import forms
from .models import PengaturanWilayah

class PengaturanWilayahForm(forms.ModelForm):
    class Meta:
        model = PengaturanWilayah
        fields = '__all__'
        labels = {
            'kabupaten_bangka': 'Kabupaten Bangka',
            'kabupaten_bangka_selatan': 'Kabupaten Bangka Selatan',
            'kabupaten_bangka_tengah': 'Kabupaten Bangka Tengah',
            'kabupaten_bangka_barat': 'Kabupaten Bangka Barat',
            'kota_pangkal_pinang': 'Kota Pangkal Pinang',
            'kabupaten_belitung': 'Kabupaten Belitung',
            'kabupaten_belitung_timur': 'Kabupaten Belitung Timur',
            # Tambahkan label lain jika perlu
        }
        # Tambahkan field lain jika perlu

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    
from .models import DataPemilu

class DataPemiluForm(forms.ModelForm):
    class Meta:
        model = DataPemilu
        fields = ['calon_1_2024', 'total_suara_2024', ]

WebsitePemilu/Pemilu/templates/Pemilu/daftar_pemilih_filter.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Daftar Pemilih Filter</title>
    <!-- <link rel="stylesheet" href="{% static 'css/styles.css' %}"> -->
    <style>

        .content {
            margin-left: 0px;
            padding-left: 40px;
            padding-right: 40px;
        }

        .card {
            border: 1px solid #ccc;
            border-radius: 10px;
            padding: 10px;
            margin: 10px;
            width: 300px;
            display: inline-block;
        }
        p {
        margin-bottom: 5px; 
        }
        #headerTitlePemilih {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 20px;
        }

        @media (max-width: 600px) {
        #headerTitlePemilihr, #headerDaftarPemilih{
            flex-direction: column; 
            text-align: center; 
        }
        #headerTitlePemilih h3,
        #headerTitlePemilih h5 {
            margin: 10px 0; 
        }
        }

        #headerDaftarPemilih {
        width: 100%;
        display: flex;
        justify-content: space-between;
        margin-left: -20px;
        margin-top: 0px;
        }

        #daftarPemilih{
            margin-left: -20px;
            margin-right: -20px;
        }
        .btn-style-1{
        background-color: #525FE1; 
        color: #ffffff; 
        border: none; 
        padding: 6px 12px; 
        border-radius: 5px; 
        height: 35px;
        text-decoration: none; 
    }
    .btn-style-1:hover {
        background-color: rgb(59, 69, 176); 
        color: #ffffff; 
        text-decoration: none; 
    }
    .btn-style-2{
        background-color: #FFA41B;
        color: #ffffff; 
        border: none; 
        padding: 6px 12px; 
        border-radius: 5px;
        height: 35px;
        text-decoration: none; 
    }
    .btn-style-2:hover {
        background-color: #c5811a; 
        color: #ffffff;
        text-decoration: none; 
    }
    .btn-style-3{
        background-color: #CC3300; 
        color: #ffffff; 
        border: none; 
        padding: 6px 12px;
        border-radius: 5px;
        height: 35px;
        text-decoration: none; 
    }
    .btn-style-3:hover {
        background-color: #952500; 
        color: #ffffff; 
        text-decoration: none; 
    }
    </style>
</head>
<body>
<div id="keseluruhan">
    <div id="headerDaftarPemilih">
        <h4>Jumlah Relawan Setelah Filter: {{ jumlah_data_setelah_filter }}</h4>
        <a href="{% url 'tambah_pemilih' %}"class="btn-style-1">Tambah Relawan</a>
    </div>

    <div class="card-container">
        {% if data_pemilih %}
            {% for pemilih in data_pemilih %}
            <div class="card shadow-sm" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title">{{ pemilih.nama }}</h5>
                    <p>NIK: <strong>{{ pemilih.nik }}</strong> </p>
                    <p>Kabupaten: {{ pemilih.kabupaten|title }}</p>
                    <p>Kecamatan: {{ pemilih.kecamatan|title }}</p>
                    <p>Kelurahan: {{ pemilih.kelurahan|title }}</p>
                    <p>TPS: {{ pemilih.tps }}</p>
                        <div class="float-end mt-2" >
                        <button type="button" class="btn-style-2" onclick="editCoordinator('{{ pemilih.id }}')">Ubah</button>
                        <button type="button" class="btn-style-3" onclick="deleteCoordinator('{{ pemilih.id }}')">Hapus</button>
                        </div>
            </div>
            </div>
            
            {% endfor %}
            
    
        {% else %}
            <p>Tidak Ada Relawan yang Terdaftar.</p>
        {% endif %}
    </div>
</div>




    
    <script>

    </script>
    


</body>
</html>

{% endblock %}

WebsitePemilu/Pemilu/templates/Pemilu/tambah_pemilih.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tambah Pemilih</title>

    <!-- <link rel="stylesheet" href="{% static 'css/styles.css' %}"> -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <style>


        .content {
            margin-left: 20px;
            margin-right: 20px;
        }

        .card {
        border: 1px solid #ccc;
        margin-bottom: 20px;
        display: flex;
        align-items: start; 
        border-radius: 15px;
        padding-left: 20px;
        padding-right: 20px;
        padding-bottom: 20px;
    }
        
        .btn-style-1{
        background-color: #525FE1; 
        color: #ffffff;
        border: none; 
        padding: 6px 12px; 
        border-radius: 5px; 
        height: 35px;
        text-decoration: none; 
        margin-top: 10px;
    }
    .btn-style-1:hover {
        background-color: rgb(59, 69, 176); 
        color: #ffffff; 
        text-decoration: none; 

    }
    

    input[type="text"] {
        width: 100%; 
    }

    .bg-terdaftar {
    background-color: rgb(95, 193, 98); 
    color: #fff; 
}

    .bg-tidakterdaftar {
        background-color: #d25f57; 
        color: #fff; 
    }

    </style>
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div>
                <h3>Tambah Relawan</h3>
            </div>

                <div class="col-md-6 mb-3">
                    <div class="card">
                        <div class="row">
                            <div class="card-body d-flex justify-content-start">
                                <div><h5 class="card-title">Cek NIK berdasarkan Data DPT</h5></div>
                            </div>
                            <div>
                                <form id="form-nik" method="post">
                                    {% csrf_token %}
                                    <input type="text" name="nik" placeholder="Masukkan NIK">
                                        <button class="btn-style-1" type="submit">Cek NIK</button>
                                </form>
                            </div>
                        </div>
                    </div>
                    <a class="btn-style-1" href="{% url 'data_pemilih' %}">Kembali ke Data Relawan </a>
                </div>

                <div class="col-md-6 mb-3">
                    <div class="card">
                        <div class="row">
                            <div class="card-body d-flex justify-content-start">
                                <div><h5 class="card-title">Data DPT</h5></div>
                            </div>
                            <div>
                                <div id="dataWarga" style="display: none;">
                                    <!-- Menampilkan informasi data warga -->
                                    <form id="form-tambah-pemilih" method="post" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        {{ form.as_p }}
                                        <label for="id_koordinator">Koordinator:</label>
                                        <select name="koordinator" id="id_koordinator">
                                            <option value="">Koordinator</option>
                                            {% for koordinator in form.koordinator.field.queryset %}
                                                <option value="{{ koordinator.id }}">{{ koordinator.nama }}</option>
                                            {% endfor %}
                                        </select>
                                        <div class="d-flex justify-content-end">
                                            <button class="btn-style-1" type="submit">Tambah Relawan</button>
                                        </div>
                                        
                                    </form>
                                </div>
                            </div>
                        </div>   
                    </div>
                </div> 
        </div>
    </div>

    <div class="modal fade" id="popupMessageModal" tabindex="-1" role="dialog" aria-labelledby="popupMessageModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="popupMessageModalLabel">Pesan</h5>
                    <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="popup-message-body">
                    <!-- Pesan akan ditampilkan di sini -->
                </div>
            </div>
        </div>
    </div>
    
    
    
    <script>
        // Tangkap form submission
        document.getElementById('form-nik').addEventListener('submit', function(event) {
            event.preventDefault(); // Hindari submit bawaan
    
            var formData = new FormData(this);
    
            // Kirim data NIK ke view untuk verifikasi
            fetch('/verifikasi-nik/', {
                method: 'POST',
                body: formData,
                headers: {
                    'X-CSRFToken': '{{ csrf_token }}' // Token CSRF dari Django
                }
            })
            .then(response => response.json())
            .then(data => {
                if (data.registered) {
                    document.getElementById('popup-message-body').classList.remove('bg-tidakterdaftar'); 
                    document.getElementById('popup-message-body').innerHTML = 'NIK terdaftar sebagai DPT';
                    $('#popupMessageModal .modal-body').addClass('bg-terdaftar'); // Tambahkan kelas untuk warna hijau
                    document.getElementById('dataWarga').style.display = 'block';

                    // Update elemen form dengan informasi dari data_warga
                    
                    document.getElementById('id_kabupaten').value = data.data_warga.kabupaten;
                    document.getElementById('id_kecamatan').value = data.data_warga.kecamatan;
                    document.getElementById('id_kelurahan').value = data.data_warga.kelurahan;

                    document.getElementById('id_nkk').value = data.data_warga.nkk;
                    document.getElementById('id_nik').value = data.data_warga.nik;
                    document.getElementById('id_nama').value = data.data_warga.nama;
                    document.getElementById('id_tempat_lahir').value = data.data_warga.tempat_lahir;
                    document.getElementById('id_tanggal_lahir').value = data.data_warga.tanggal_lahir;
                    document.getElementById('id_sts_kawin').value = data.data_warga.sts_kawin;
                    document.getElementById('id_kelamin').value = data.data_warga.kelamin;
                    document.getElementById('id_alamat').value = data.data_warga.alamat;
                    document.getElementById('id_rt').value = data.data_warga.rt;
                    document.getElementById('id_rw').value = data.data_warga.rw;
                    document.getElementById('id_disabilitas').value = data.data_warga.disabilitas;
                    document.getElementById('id_ektp').value = data.data_warga.ektp;
                    document.getElementById('id_tps').value = data.data_warga.tps;

                } else {
                    document.getElementById('popup-message-body').innerHTML = 'NIK tidak terdaftar sebagai DPT';
                    $('#popupMessageModal .modal-body').addClass('bg-tidakterdaftar');
                    document.getElementById('dataWarga').style.display = 'none';
                }
                $('#popupMessageModal').modal('show'); 
            });
        });

        document.getElementById('form-tambah-pemilih').addEventListener('submit', function (event) {
        event.preventDefault();

        var formData = new FormData(this);
        fetch('/tambah-pemilih/', {
            method: 'POST',
            body: formData,
            headers: {
                'X-CSRFToken': '{{ csrf_token }}'
            }
        })
        .then(response => {
            if (response.ok) {
                return response.json();
            } else {
                throw new Error('Network response was not ok.');
            }
        })
        .then(data => {
            if (data.success) {
                document.getElementById('popup-message-body').classList.remove('bg-tidakterdaftar'); // Menghapus kelas warna merah
                document.getElementById('popup-message-body').innerHTML = data.message;
                $('#popupMessageModal .modal-body').addClass('bg-terdaftar');
                $('#popupMessageModal').on('hidden.bs.modal', function (e) {
                    window.location.href = data.redirect;
                });
            } else {
                document.getElementById('popup-message-body').innerHTML = data.message;
                $('#popupMessageModal .modal-body').addClass('bg-tidakterdaftar');
            }
            $('#popupMessageModal').modal('show');
        })
        .catch(error => {
            console.error('Error:', error);
        });
    });


    </script>
    


</body>
</html>

{% endblock %}